DQA-012
beshketo/demo-qa pull request #25
Opened 2024-10-22 21:57 UTC by beshketo

Added 4 test for Book Store Page

2024-10-29 08:22 UTC, DzigMS requested changes

2024-10-29 08:22 UTC, DzigMS commented on bookstore-application/src/test/java/parallel/BookStoreTest.java
> +        System.out.println("partTitle: " + partTitle);
Delete print to console from code.
I guess it's for debugging only.

2024-10-29 08:22 UTC, DzigMS commented on bookstore-application/src/test/java/parallel/BookStoreTest.java
> +        System.out.println("author: " + author);
The same...

2024-10-29 08:22 UTC, DzigMS commented on bookstore-application/src/test/java/parallel/BookStoreTest.java
> +        System.out.println("userName: " + userName);
And again...

2024-10-30 06:02 UTC, beshketo reviewed
i did changes

2024-10-30 06:03 UTC, merged